source 'http://rubygems.org'
source 'http://gems.github.com'

gem 'rake'
gem 'sqlite3-ruby'
gem 'sequel'
gem 'sinatra'
gem 'thin'
gem 'unicorn'
gem 'httpclient'
gem 'SystemTimer'
gem 'json'
gem 'crack'
gem 'ratom'
gem 'ruby-hmac'
gem 'eventmachine'
